
logging:
  level:
    org.springframework.web: info
    com.mayikt: info

#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates
    application:
        name: app-mayikt-portal-web
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
server:
  port: 8010

redis:
 hostname: 192.168.33.13
 port: 6379



xxl-sso:
  excluded:
    paths:
xxl:
  sso:
    server: http://xxlssoserver.com:8080/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: redis://192.168.33.13:6379
